### ISSUE TITLE
寻求实验结果

### ISSUE THREAD

**Issue by zhou431496** [youngLBW/HRN#1]
hi, 工作十分出色。请问您能公开在FaceScape-lab各个旋转角度的预测结果嘛。谢谢

**Comment by youngLBW** [comment]
> hi, 工作十分出色。请问您能公开在FaceScape-lab各个旋转角度的预测结果嘛。谢谢

您好，谢谢您的关注！我们即将公开我们的代码和模型，届时您可以直接用模型跑预测结果哈~

**Comment by zhou431496** [comment]
hi, 能否给我们发一个你在Facescape基准对齐的代码嘛，这个对齐每个方法都不一样。如果可以我们十分感谢。

**Comment by youngLBW** [comment]
hi, 我们的对齐代码与facescape benchmark中的"Deep3DFaceRec"方法是一致的，也就是https://github.com/zhuhao-nju/facescape/blob/master/benchmark/code/pred_loader.py 中的align_deep3df()函数，只是包含cropping信息的json文件会有一点变化，这个会随代码一起公开哈

**Comment by zhou431496** [comment]
十分感谢

**Comment by zhou431496** [comment]
嗨，能不能提供您在FaceScape基准的模型嘛，因为我们马上要投稿了，我们希望能和您的工作进行比较，以此来引用您的工作。

**Comment by youngLBW** [comment]
hello，我们最近还在整理，预计下周中左右会公布代码和模型，不知道这对您是否来得及

**Comment by zhou431496** [comment]
十分抱歉，我们论文可能周一就会投出去，如果方便，可以加个微信嘛。我目前在读硕士，即将读博。

**Comment by youngLBW** [comment]
可以的，你可以把微信号发我邮件（biwen1996@gmail.com)，我加你

**Comment by zhou431496** [comment]
谢谢

**Comment by Bys35271** [comment]
> hello，我们最近还在整理，预计下周中左右会公布代码和模型，不知道这对您是否来得及

同求代码开源时间，想要复现学习您的项目挺久了

**Comment by youngLBW** [comment]
> > hello，我们最近还在整理，预计下周中左右会公布代码和模型，不知道这对您是否来得及
> 
> 同求代码开源时间，想要复现学习您的项目挺久了

感谢您的关注，预计最早这周末，最晚下周二三的样子会进行代码和模型的开源哈

**Comment by Bys35271** [comment]
> > > hello，我们最近还在整理，预计下周中左右会公布代码和模型，不知道这对您是否来得及
> > 
> > 
> > 同求代码开源时间，想要复现学习您的项目挺久了
> 
> 感谢您的关注，预计最早这周末，最晚下周二三的样子会进行代码和模型的开源哈

好的，感谢！
