### ISSUE TITLE
Video?

### ISSUE THREAD

**Issue by emlcpfx** [youngLBW/HRN#10]
Hi, can this run on every frame of a video?

**Comment by youngLBW** [comment]
Hi, We haven't tried this yet. I suppose the major challenge should be the consistency between frames. If there are relevant experimental results in the future, we will share them with you.

**Comment by emlcpfx** [comment]
The most temporally stable one of these 3D face fitting repos I’ve tried is 3DDFA_V2. I think that’s open source. I wonder if you can use their smoothing algorithm that they call in demo_video_smooth.py.
