### ISSUE TITLE
纹理图分辨率

### ISSUE THREAD

**Issue by ZHongshuang** [youngLBW/HRN#11]
谢谢你开源的模型，为我提供了很多的帮助，我有几个问题想请教您。

我之前使用了modelscope开源的模型，很高清，但是眼部纹理会有像是粘贴上去的问题。
直接用github上的代码运行时，眼部纹理问题消失了，但是分辨率只有256了，比较模糊，我想问下这两个模型的区别是什么，有办法提升纹理图分辨率吗？

谢谢！！

**Comment by youngLBW** [comment]
您好，之前modelscope的模型不是用的HRN，里面对贴图增加了一些人脸超分增强的后处理，现在更新为纯粹的HRN了，就把那些额外的模块去掉了。要提升现有的分辨率，一方面是可以在models/facerecon_model.py里的line401~line424部分的纹理拟合部分，去调整renderer、texture这些的分辨率，这个部分后面有时间我会更新github代码；另外一方面，也可以在纹理图的结果上进行超分、增强，modelscope上有直接可以试用的模型：https://www.modelscope.cn/models/damo/cv_gpen_image-portrait-enhancement/summary

**Comment by ZHongshuang** [comment]
感谢您的回复～
