### ISSUE TITLE
使用中出现的问题

### ISSUE THREAD

**Issue by x-ray990011** [youngLBW/HRN#37]
感谢您的辛勤工作，我搭好环境后，使用过程中报错
![image](https://github.com/youngLBW/HRN/assets/127190335/2a62bcdf-e855-4796-93f4-51632cd7364a)
您能帮我解答一下吗

**Comment by Dcvu233** [comment]
换face_alignment版本或者进去LandmarksType改源码，_3D=3

**Comment by xiaoli4881** [comment]
loading the model from assets/pretrained_models/hrn_v1.1/epoch_10.pth
Downloading: "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" to /home/ver/.cache/torch/hub/checkpoints/s3fd-619a316812.pth
  1%|          | 728k/85.7M [06:10<11:45:55, 2.10kB/s]  下载权重文件太慢了，科学上网也不行啊

**Comment by youngLBW** [comment]
> loading the model from assets/pretrained_models/hrn_v1.1/epoch_10.pth Downloading: "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" to /home/ver/.cache/torch/hub/checkpoints/s3fd-619a316812.pth 1%| | 728k/85.7M [06:10<11:45:55, 2.10kB/s] 下载权重文件太慢了，科学上网也不行啊

您好，可以在https://pre.modelscope.cn/models/damo/cv_resnet50_face-reconstruction/files这里下载哈，然后放到/home/ver/.cache/torch/hub/checkpoints这里。
