### ISSUE TITLE
给遇到同样问题者face_alignment.LandmarksType._3D attribute None

### ISSUE THREAD

**Issue by 675492062** [youngLBW/HRN#43]
face_alignment最新版已做修改（https://pypi.org/project/face-alignment/）
face_alignment.LandmarksType._3D--->face_alignment.LandmarksType.THREE_D

希望有其他问题的一起将问题和解答补充在下面，搞一个集合帖。

**Comment by juny-park-95** [comment]
thank you for your comment. I really helpful.

**Comment by yltqy** [comment]
you are my hero,thx bro

**Comment by NewtOliver** [comment]
我降了版本也能用
