### ISSUE TITLE
vertex

### ISSUE THREAD

**Issue by tankchenggeng** [youngLBW/HRN#48]
我理解的这个项目，人脸的高频细节，如皱纹、酒窝等，似乎是在最后将3DMM重建后的面部render出的图像，与原始图像进行一些运算得到的。有没有可能将这种高频细节的结果反向应用回3DMM的模型，去修正顶点的位置呢？如果能修正3DMM模型的顶点位置，项目的价值又可以向前一大步了

**Comment by youngLBW** [comment]
您好，这块是有的，结果的输出是包含了一个xxx_hrn_high_mesh.obj的文件，这个就是把高频细节作用到3dmm模型上的结果。如果您那边没有这个输出的话，可以重新pull一下代码试试。

**Comment by tankchenggeng** [comment]
不好意思，现在才看到消息，感谢您的回复。我再确认一下看看
