### ISSUE TITLE
when i run multi-view get error but single no problem

### ISSUE THREAD

**Issue by 1406428260** [youngLBW/HRN#5]
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 35709]],
which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed
to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by youngLBW** [comment]
Hi, which version of pytorch are you using?

**Comment by fabricecarles** [comment]
Same error here, In my case the solution was to install pytorch==1.6.0 in a python 3.8 conda environment that allow after to follow pytorch3d install https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md

@youngLBW 
maybe you can update readme with
* Python >= 3.8
* PyTorch == 1.6

**Comment by youngLBW** [comment]
> Same error here, In my case the solution was to install pytorch==1.6.0 in a python 3.8 conda environment that allow after to follow pytorch3d install https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md
> 
> @youngLBW maybe you can update readme with
> 
> * Python >= 3.8
> * PyTorch == 1.6

Thanks for your sharing! The readme has been updated.

**Comment by Bys35271** [comment]
I also met this problem, the code that raise the error is "loss_all.backward()" in def forward_mvhrn().
I still can not solve it well.  Following is my package version.  Is this problem caused by version?
Python 3.10
Pytorch 1.11.0

**Comment by youngLBW** [comment]
I re-implemented this error, and fix it by adding .clone() to https://github.com/youngLBW/HRN/blob/main/models/losses.py#L201, the code has been updated.
