### ISSUE TITLE
怎样将生成的纹理贴图贴到生成的obj模型上

### ISSUE THREAD

**Issue by xiaozhang0927** [youngLBW/HRN#51]
![image](https://github.com/youngLBW/HRN/assets/127761312/5f998255-3b7f-41c5-8a6c-79e81e1cb3b5)
请问怎样可以将生成的纹理贴图贴到生成的obj模型上

**Comment by tjuqxb** [comment]
meshlab 或者建模软件（Blender）直接贴

**Comment by youngLBW** [comment]
您好，如果这是hrn_mid_mesh.obj的话，你可以像楼上说的直接把它拖到meshlab或者其他建模软件里面。如果是hrn_high_mesh.obj的话，我们目前还没有把uv放进去，所以无法使用贴图，但我们近期会实现这个功能。

**Comment by CanYuanA** [comment]
> 您好，如果这是hrn_mid_mesh.obj的话，你可以像楼上说的直接把它拖到meshlab或者其他建模软件里面。如果是hrn_high_mesh.obj的话，我们目前还没有把uv放进去，所以无法使用贴图，但我们近期会实现这个功能。

您好，感谢您团队的工作，请问对于生成高频变形后的uv图像是否还有计划？我在尝试理解代码的过程里发现了这个问题。
