### ISSUE TITLE
Putting texture onto mesh for multiview reconstruction

### ISSUE THREAD

**Issue by yumikim381** [youngLBW/HRN#8]
Thank you for your great work and publishing them!
For single view image reconstruction, i could use the texture jpeg in the results and set Texture using Meshlab but when i try to do the same for the resulting mesh of multiview reconstruction, i get this following error: 

![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/91d0ec44-d741-46e0-8f80-b398c051e46f/Untitled.png)
Could you please explain how you put the texture to the resulting face meshes as in demos? 
Thank you a lot !

**Comment by youngLBW** [comment]
I'm sorry I didn't quite understand your question, the image you uploaded seems to be failing and I can't read it. Can you re-upload the picture or send it to me via email?
