### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by rlczddl** [youngLBW/HRN#9]
在补充材料里面看到了有做完整人头的重建，里面提到“In addition, we unwrap the new head model and recalculate a new set of UV coordinates.”想问下，这个展开是用什么软件做的嘛？

**Comment by youngLBW** [comment]
这个没有用软件，是我们自己实现的一个简单的圆柱形uv展开。这样展开的优点是可以得到完整连续的uv贴图，缺点是在耳朵部分会有一定的uv错乱，不过对效果影响不大。软件的话好像blender可以进行自动uv展开，您可以找一下相关的教程。

**Comment by rlczddl** [comment]
了解了，感谢回复。还有个问题想请教下，就是关于FaceHD-100数据集，多视角图片重建三维网格，是采用了什么算法？colmap,openmvs,pmvs这种嘛？

**Comment by youngLBW** [comment]
我们用的是“reality capture”这个软件进行重建的，里面用到的算法应该是类似于colmap, openmvs这种

**Comment by rlczddl** [comment]
了解了，感谢回复！

**Comment by rlczddl** [comment]
你好，不知道完整人头部分的代码后续会开源么？

**Comment by youngLBW** [comment]
> 你好，不知道完整人头部分的代码后续会开源么？

这个目前还没有计划哈，因为人头部分还不太成熟，我们还在持续迭代中，后续有好的效果会更新的哈

**Comment by rlczddl** [comment]
了解了
